[repository]
REPOSITORY_NAME = "example-project"

# A list of secrets used by the Operators in this repository
OPERATORS_SECRETS = [
    "GITHUB_ACCESS_TOKEN"
]

# OLD VARS - TO BE REMOVED
# FLOWUI_DEPLOY_MODE = "local-bash"
# VOLUME_MOUNT_PATH_HOST = "/media/luiz/storage/Github/flowui_example_project/mnt/fs"
# FLOWUI_PATH_HOST = "/media/luiz/storage/Github/flowui"
# CODE_REPOSITORY_SOURCE = "local"
# GITHUB_REPOSITORY_NAME = "Tauffer-Consulting/flowui_example_project"